language: node_js
node_js: 14.9

before_install:
  - yarn add codecov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
  - yarn semantic-release

branches:
  only:
    - master
